ci: add distroless image
aureq/cert-manager-webhook-ovh pull request #5
Opened 2022-11-07 01:44 UTC by TartanLeGrand

Add distroless image for size, use non-root user and add ide to gitignore.

2022-11-07 08:22 UTC, aureq commented on Dockerfile
> +FROM gcr.io/distroless/base-debian11
Could you please point out the benefits of using a distroless base image?

2022-11-22 03:34 UTC, aureq commented
@TartanLeGrand have you seen my comments above ?

2022-11-24 06:11 UTC, TartanLeGrand commented
@aureq I have no comments from you in this PR. Have you been send your review ?

2022-11-24 07:25 UTC, aureq requested changes

2022-11-24 07:26 UTC, aureq commented
> @aureq I have no comments from you in this PR. Have you been send your review ?

I did not 🤦‍♂️ though you should be able to see them now.

2022-11-25 12:20 UTC, TartanLeGrand commented on Dockerfile
> +COPY --from=build /sbin/getcap /sbin
Mistake for debuging.

2022-11-25 12:31 UTC, TartanLeGrand commented on Dockerfile
> +FROM gcr.io/distroless/base-debian11
Size and security vs alpine image

2022-11-25 12:40 UTC, TartanLeGrand commented on Dockerfile
> +RUN ["/sbin/setcap", "cap_net_bind_service=+ep", "/app"]
it doesn't change anything to the execution of the command. It is just not put in the /usr/local/bin folder and that the command is not called webhook and that I used a more generic term.

2022-11-25 12:43 UTC, TartanLeGrand commented on Dockerfile
> +USER nonroot:nonroot
The `nonroot` user is the user created in the distroless image, this is to match the distroless convention.

2022-12-10 23:17 UTC, merged

2022-12-11 01:17 UTC, aureq commented
I've partially merged your PR, thank you for this contribution.

For the purpose of transparency, the base images will remain on Alpine Linux for the following reasons:

- `gcr.io/distroless/base-debian11:latest` is 20.3MB and has 13 reported [vulnerabilities](https://trivy.dev/results/?image=gcr.io/distroless/base-debian11)
- `alpine:3.16` is 5.54MB and has no reported [vulnerabilities](https://trivy.dev/results/?image=alpine:3.16)